### ISSUE TITLE
服务器部署成功怎么查看日志

### ISSUE THREAD

**Issue by jiankong123** [rongchenlin/BiliBili-Lucky-Draw#11]
![image](https://github.com/rongchenlin/BiliBili-Lucky-Draw/assets/127178651/6e0c0450-769d-4889-b2c0-03aa471a28e0)
如图，容器运行后怎么查看日志呀
还有多用户怎么设置

**Comment by rongchenlin** [comment]
1. 日志目前应该是可以在docker容器中查看，后期也将完善日志收集和管理功能。
2. 多用户目前正在迭代，后期将会发布 windows桌面程序，并在windows桌面程序版本中增加多用户功能。

**Comment by jiankong123** [comment]
我昨天部署的容器已经启动，今天看动态没有运行，也看不到日志

**Comment by jiankong123** [comment]
> 

![image](https://github.com/rongchenlin/BiliBili-Lucky-Draw/assets/127178651/55594f17-5f0d-47dd-aac6-ee3aeb0f22ac)
去宝塔看了下日志，这是什么原因

**Comment by rongchenlin** [comment]
在docker中使用docker log查看
