### ISSUE TITLE
win桌面程序运行无转发

### ISSUE THREAD

**Issue by Camille672** [rongchenlin/BiliBili-Lucky-Draw#15]
大大，我用win桌面程序运行时，替换了匹配的chromedriver，登陆扫描都正常，显示开始转发，转发结束，但是发现并未发生转发操作，账号动态界面无新内容，几天了都是这样，是正常的吗(ㄒoㄒ)

**Comment by rongchenlin** [comment]
目前关闭桌面版程序，已经更新Docker版本。
