### ISSUE TITLE
数据库问题

### ISSUE THREAD

**Issue by Starduster-lin** [rongchenlin/BiliBili-Lucky-Draw#2]
dalao救救孩子吧！除开日志表以外，fans、share、 users_cnt这三个表，都没能插入获取到数据，是不是我有什么遗漏的地方吗？  dalao您写的去挖掘那些经常转发抽奖动态的伙伴，这个需要事先在某处填入 经常转发抽奖动态的账号uid吗（例如b站大锦鲤）？

**Comment by rongchenlin** [comment]
报错内容是什么？Chrome和驱动的版本是否一致？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月9日(周日) 晚上11:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [rongchenlin/BiliBili-Lucky-Draw] 数据库问题 (Issue #2)




 
dalao救救孩子吧！除开日志表以外，fans、share、 users_cnt这三个表，都没能插入获取到数据，是不是我有什么遗漏的地方吗？  dalao您写的去挖掘那些经常转发抽奖动态的伙伴，这个需要事先在某处填入 经常转发抽奖动态的账号uid吗（例如b站大锦鲤）？

**Comment by Starduster-lin** [comment]
驱动没问题

"start ..."
INFO:root:2023-04-10 11:29:33

DevTools listening on ws://127.0.0.1:49873/devtools/browser/6a958f34-62dc-4fa0-92c7-92f8cb2a3b9c
INFO:root:login by cookie success !
_insert:insert into t_log(function_name,content,note,ip,insert_time) values('get_fans_list','获取用户列表出错：<class pymysql.err.OperationalError>','p0','192.168.3.52','2023-04-10 11:29:43.938945')
ERROR:root:(1525, "Incorrect DATETIME value: '2023'")
_insert:insert into t_log(function_name,content,note,ip,insert_time) values('start_forward','转发动态出错：<class TypeError>','p1','192.168.3.52','2023-04-10 11:29:44.129909')
INFO:root:2023-04-10 11:29:44
INFO:root:开始转发
_insert:insert into t_log(function_name,content,note,ip,insert_time) values('send_start_forward','筛选任务开始发送通知出错：<class UnboundLocalError>','无','192.168.3.52','2023-04-10 11:29:44.285909')
INFO:root:start main task

**Comment by Starduster-lin** [comment]
弄了一天，往t_user_cnt添加了一个记录，可以正常执行了

**Comment by rongchenlin** [comment]
我看到了，程序里有个通知推送，我忘记改了，推送到我这了，晚上重推一版。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月10日(周一) 下午4:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rongchenlin/BiliBili-Lucky-Draw] 数据库问题 (Issue #2)




 
弄了一天，往t_user_cnt添加了一个记录，可以正常执行了

**Comment by rongchenlin** [comment]
后期打算弄到docker里，这样大家部署方便点



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月10日(周一) 下午4:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rongchenlin/BiliBili-Lucky-Draw] 数据库问题 (Issue #2)




 
弄了一天，往t_user_cnt添加了一个记录，可以正常执行了

**Comment by Starduster-lin** [comment]
> 后期打算弄到docker里，这样大家部署方便点
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年4月10日(周一) 下午4:28 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [rongchenlin/BiliBili-Lucky-Draw] 数据库问题 (Issue #2) 弄了一天，往t_user_cnt添加了一个记录，可以正常执行了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

辛苦dalao，期待dalao的docker
