### ISSUE TITLE
使用境外服务器部署, 用户动态页面白屏, 但手动登录没有问题

### ISSUE THREAD

**Issue by jackzzs** [rongchenlin/BiliBili-Lucky-Draw#22]
原因是登录时没有设定部分 cookie, 导致访问动态接口返回 352 错误.
详见: https://github.com/SocialSisterYi/bilibili-API-collect/issues/686
希望优化登录方法, 谢谢.

**Comment by rongchenlin** [comment]
好的，欢迎您提供更加详细的信息，更加欢迎您给本项目提PR一起解决这个问题。
