### ISSUE TITLE
运行成功后点击进入 your_ip:5555/ui/sessions edge浏览器提示Unable to find resource, invalid path in url.

### ISSUE THREAD

**Issue by jiuyuan233** [rongchenlin/BiliBili-Lucky-Draw#35]
### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 复现步骤 🕹

C:\BiliBili-Lucky-Draw-master>docker-compose up -d
[+] Running 1/4
[+] Running 2/4bili-lucky-draw-master_default            Created                                                   2.7s
 - Network bilibili-lucky-draw-master_default            Created                                                   2.8s
[+] Running 2/4ili-selenium                               Started                                                   2.6s
 - Network bilibili-lucky-draw-master_default            Created                                                   2.9s
[+] Running 2/4ili-selenium                               Started                                                   2.6s
 - Network bilibili-lucky-draw-master_default            Created                                                   3.0s
[+] Running 2/4ili-selenium                               Started                                                   2.6s
 - Network bilibili-lucky-draw-master_default            Created                                                   3.1s
[+] Running 2/4ili-selenium                               Started                                                   2.6s
 - Network bilibili-lucky-draw-master_default            Created                                                   3.2s
[+] Running 2/4ili-selenium                               Started                                                   2.6s
 - Network bilibili-lucky-draw-master_default            Created                                                   3.3s
[+] Running 2/4ili-selenium                               Started                                                   2.6s
 - Network bilibili-lucky-draw-master_default            Created                                                   3.4s
[+] Running 2/4ili-selenium                               Started                                                   2.6s
 - Network bilibili-lucky-draw-master_default            Created                                                   3.5s
[+] Running 2/4ili-selenium                               Started                                                   2.6s
 - Network bilibili-lucky-draw-master_default            Created                                                   3.6s
[+] Running 2/4ili-selenium                               Started                                                   2.6s
 - Network bilibili-lucky-draw-master_default            Created                                                   3.7s
[+] Running 2/4ili-selenium                               Started                                                   2.6s
 - Network bilibili-lucky-draw-master_default            Created                                                   3.8s
[+] Running 2/4ili-selenium                               Started                                                   2.6s
 - Network bilibili-lucky-draw-master_default            Created                                                   3.9s
[+] Running 2/4ili-selenium                               Started                                                   2.6s
 - Network bilibili-lucky-draw-master_default            Created                                                   4.0s
[+] Running 2/4ili-selenium                               Started                                                   2.6s
 - Network bilibili-lucky-draw-master_default            Created                                                   4.1s
[+] Running 3/4ili-selenium                               Started                                                   2.6s
 - Network bilibili-lucky-draw-master_default            Created                                                   4.1s
 ✔ Container bili-selenium                               Started                                                   2.6s
 ✔ Container bili-db                                     Started                                                   2.5s
 ✔ Container bilibili-lucky-draw-master-dynamic_share-1  Started                                                   3.5s

C:\BiliBili-Lucky-Draw-master>
![BCF6DC14A15CEC52EB8D65B6090F9272](https://github.com/rongchenlin/BiliBili-Lucky-Draw/assets/119844446/0a9d086f-713b-41a8-86bf-dc5bf3257449)

### 问题描述 😯

![Uploading BCF6DC14A15CEC52EB8D65B6090F9272.png…]()

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by rongchenlin** [comment]
程序启动和运行过程是否有报错信息？

**Comment by jiuyuan233** [comment]
没有报错啊我又从新弄了一遍也没有
[3_24.txt](https://github.com/rongchenlin/BiliBili-Lucky-Draw/files/14733362/3_24.txt)
![1](https://github.com/rongchenlin/BiliBili-Lucky-Draw/assets/119844446/266539bf-7926-4abb-8cc0-4105f223e505)
![2](https://github.com/rongchenlin/BiliBili-Lucky-Draw/assets/119844446/ed170f04-55a5-4131-b4cd-635b9c7b1117)

**Comment by Gnlop** [comment]
Traceback (most recent call last):
2024-06-19 11:21:31   File "/app/service/share_service/share_one_dynamic.py", line 163, in click_share
2024-06-19 11:21:31     share_text_old = ElementUtil.get_element_by_xpath(bro, chains,
2024-06-19 11:21:31                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-19 11:21:31   File "/app/utils/webdriver_util.py", line 21, in get_element_by_xpath
2024-06-19 11:21:31     return WebDriverWait(bro, 10).until(EC.element_to_be_clickable((By.XPATH, path)))
2024-06-19 11:21:31            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-19 11:21:31   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 89, in until
2024-06-19 11:21:31     raise TimeoutException(message, screen, stacktrace)

**Comment by Gnlop** [comment]
我也有同样的问题 在检擦bilibili-lucky-draw-dynamic_share-1时候发现似乎是xpath的路径有问题
