### ISSUE TITLE
 不运行

### ISSUE THREAD

**Issue by jiuyuan233** [rongchenlin/BiliBili-Lucky-Draw#39]
### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 问题描述 😯

![image](https://github.com/rongchenlin/BiliBili-Lucky-Draw/assets/119844446/81e1393b-b87b-4316-9f60-334552860aaa)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by sissin0125** [comment]
如何解决的  我也是这样

**Comment by acgurl** [comment]
如何解决的 我也是这样
