### ISSUE TITLE
部署时遇到的坑

### ISSUE THREAD

**Issue by Starduster-lin** [rongchenlin/BiliBili-Lucky-Draw#4]
小白一枚，我大致的捣鼓如下：

最初数据库没记录，当执行def select_user_by_hour时查询不到记录，自行往t_user_cnt表插入一条记录就行了（id位数可以多一点，太小的老用户一般不转发抽奖）

**Comment by karhow** [comment]
就是要找到一个拥有初始的转发抽奖的用户的一条记录吗？
