### ISSUE TITLE
避免Docker时区错误

### ISSUE THREAD

**Issue by sasa012** [rongchenlin/BiliBili-Lucky-Draw#8]
Dockerfile文件中可加入以下参数避免时区错误
`# 设置时区`
`RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone`

![image](https://github.com/rongchenlin/BiliBili-Lucky-Draw/assets/57254576/841b4b3f-31f3-4e96-b12a-0c702dbd514b)

**Comment by rongchenlin** [comment]
好的，感谢大佬的指点！后续更新将加入这个问题的修复。
